### ISSUE TITLE
Deferred EntityManager building breaks Backoffice entities replacements

### ISSUE THREAD

**Issue by dpgover** [digbang/security#3]
Detected in `doctrine:schema:update`

Commit 1b833b028b7ae4b2e35a19a5ac007feec5588d72

**Comment by guiwoda** [comment]
Podés elaborar?
Un stack trace al menos? :sweat_smile:

**Comment by guiwoda** [comment]
Fixed by https://github.com/digbang/security/commit/46c979f30a9c5e6143d5d18f01220c2e8556bcb2
